import { Category } from '../model/category';

// Public Cost
const PUBLIC_CATEGORY_FOOD              = 10;
const PUBLIC_CATEGORY_DAILY_NECESSITIES = 11;
const PUBLIC_CATEGORY_RELATIINSHIP      = 12;
const PUBLIC_CATEGORY_HOBBY             = 13;
const PUBLIC_CATEGORY_HOUSE             = 14;
const PUBLIC_CATEGORY_ETC               = 19;

// Private Cost
const PRIVATE_CATEGORY_FOOD         = 20;
const PRIVATE_CATEGORY_RELATIINSHIP = 21;
const PRIVATE_CATEGORY_BEAUTY       = 22;
const PRIVATE_CATEGORY_ETC          = 29;

export const PUBLIC_CATEGORY_LIST = {
  [PUBLIC_CATEGORY_FOOD]: '食費',
  [PUBLIC_CATEGORY_DAILY_NECESSITIES]: '日用品',
  [PUBLIC_CATEGORY_RELATIINSHIP]: '交際',
  [PUBLIC_CATEGORY_HOBBY]: '旅行・本・趣味',
  [PUBLIC_CATEGORY_HOUSE]: '住まい',
  [PUBLIC_CATEGORY_ETC]: 'その他'
};

export const PRIVATE_CATEGORY_LIST = {
  [PRIVATE_CATEGORY_FOOD]: '食費',
  [PRIVATE_CATEGORY_RELATIINSHIP]: '交際',
  [PRIVATE_CATEGORY_BEAUTY]: '服・美容',
  [PRIVATE_CATEGORY_ETC]: 'その他'
};

export const publicCategory: Category[] = [
  { value: PUBLIC_CATEGORY_FOOD,              viewValue: PUBLIC_CATEGORY_LIST[PUBLIC_CATEGORY_FOOD] },
  { value: PUBLIC_CATEGORY_DAILY_NECESSITIES, viewValue: PUBLIC_CATEGORY_LIST[PUBLIC_CATEGORY_DAILY_NECESSITIES] },
  { value: PUBLIC_CATEGORY_RELATIINSHIP,      viewValue: PUBLIC_CATEGORY_LIST[PUBLIC_CATEGORY_RELATIINSHIP] },
  { value: PUBLIC_CATEGORY_HOBBY,             viewValue: PUBLIC_CATEGORY_LIST[PUBLIC_CATEGORY_HOBBY] },
  { value: PUBLIC_CATEGORY_HOUSE,             viewValue: PUBLIC_CATEGORY_LIST[PUBLIC_CATEGORY_HOUSE] },
  { value: PUBLIC_CATEGORY_ETC,               viewValue: PUBLIC_CATEGORY_LIST[PUBLIC_CATEGORY_ETC] },
];

export const privateCategory: Category[] = [
  { value: PRIVATE_CATEGORY_FOOD,         viewValue: PRIVATE_CATEGORY_LIST[PRIVATE_CATEGORY_FOOD] },
  { value: PRIVATE_CATEGORY_RELATIINSHIP, viewValue: PRIVATE_CATEGORY_LIST[PRIVATE_CATEGORY_RELATIINSHIP] },
  { value: PRIVATE_CATEGORY_BEAUTY,       viewValue: PRIVATE_CATEGORY_LIST[PRIVATE_CATEGORY_BEAUTY] },
  { value: PRIVATE_CATEGORY_ETC,          viewValue: PRIVATE_CATEGORY_LIST[PRIVATE_CATEGORY_ETC] },
];
